Added init with options
micro-ROS/rclc pull request #32
Opened 2020-06-03 13:56 UTC by pablogs9

This PR adds a convenience function for init with options: `rclc_support_init_with_options`.

This init function is required when default options from `rcl_get_zero_initialized_init_options` and `rcl_init_options_init` are not enough. For example when configuring underlying RMW in micro-ROS.

Please let me know your opinions about this feature.

2020-06-03 14:13 UTC, JanStaschulat requested changes
Looks good to me, just update the unit tests.

2020-06-03 14:13 UTC, JanStaschulat commented on rclc/test/rclc/test_init.cpp
> +  rc = rclc_support_init(nullptr, 0, nullptr, &allocator);
@pablogs9 use also `rclc_support_init_with_options` function

2020-06-03 14:13 UTC, JanStaschulat commented on rclc/test/rclc/test_init.cpp
> +  rc = rclc_support_init(&support, 0, nullptr, nullptr);
@pablogs9 use also `rclc_support_init_with_options` function as well.

2020-06-03 14:56 UTC, pablogs9 commented on rclc/test/rclc/test_init.cpp
> +  rc = rclc_support_init(nullptr, 0, nullptr, &allocator);
Done!

2020-06-03 14:56 UTC, pablogs9 commented on rclc/test/rclc/test_init.cpp
> +  rc = rclc_support_init(&support, 0, nullptr, nullptr);
Done!

2020-06-03 14:59 UTC, JanStaschulat submitted a review, later dismissed

2020-06-08 05:46 UTC, julionce reviewed
I review it in https://github.com/micro-ROS/rclc/pull/33.

2020-06-08 06:10 UTC, pablogs9 commented
Changes applied

2020-06-08 06:53 UTC, julionce approved these changes

2020-06-08 17:37 UTC, JanStaschulat approved these changes

2020-06-09 05:07 UTC, merged